# Generated by Django 6.0.4 on 2026-05-07 19:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id_trabajo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('id_categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('pago_cliente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pago_trabajador', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pago_retenido', models.BooleanField(default=True)),
                ('xp_otorgada', models.IntegerField(blank=True, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('foto_trabajo', models.TextField(blank=True, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actividad', models.DateTimeField(auto_now=True)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('tiempo_estimado_horas', models.IntegerField(blank=True, null=True)),
                ('es_tarea_premium', models.BooleanField(default=False)),
                ('prioridad_suscripcion', models.IntegerField(default=0)),
                ('borrado_por_publicador', models.BooleanField(default=False)),
                ('borrado_por_trabajador', models.BooleanField(default=False)),
                ('confirmacion_publicador', models.CharField(blank=True, max_length=50, null=True)),
                ('confirmacion_trabajador', models.CharField(blank=True, max_length=50, null=True)),
                ('xp_ajustado_por_valoracion', models.BooleanField(default=False)),
                ('nota_sistema', models.TextField(blank=True, null=True)),
                ('admin_leido', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'trabajos',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('uid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=150, null=True)),
                ('nombre_completo', models.CharField(blank=True, max_length=255, null=True)),
                ('dni', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion_principal', models.TextField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('foto_perfil', models.TextField(blank=True, null=True)),
                ('curriculum_url', models.TextField(blank=True, null=True)),
                ('nivel', models.IntegerField(default=1)),
                ('experiencia_total', models.IntegerField(default=0)),
                ('experiencia_nivel_actual', models.IntegerField(default=0)),
                ('tareas_realizadas', models.IntegerField(default=0)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dinero_ganado_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('especialidad_principal', models.CharField(blank=True, max_length=100, null=True)),
                ('puntos_especialidad', models.IntegerField(default=0)),
                ('id_suscripcion_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_vencimiento_cliente', models.DateTimeField(blank=True, null=True)),
                ('renovacion_automatica_cliente', models.BooleanField(default=False)),
                ('id_suscripcion_trabajador', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_vencimiento_trabajador', models.DateTimeField(blank=True, null=True)),
                ('renovacion_automatica_trabajador', models.BooleanField(default=False)),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('ultimo_login_suscrito', models.BooleanField(default=False)),
                ('valoracion_media', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('num_valoraciones', models.IntegerField(default=0)),
                ('stats_diarias', models.JSONField(blank=True, null=True)),
                ('baneado', models.BooleanField(default=False)),
                ('baneado_hasta', models.DateTimeField(blank=True, null=True)),
                ('motivo_baneo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'ordering': ['nombre_completo', 'email'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioEliminado',
            fields=[
                ('id_log', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('uid_original', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=150, null=True)),
                ('dni', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_eliminacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuarios_eliminados',
                'ordering': ['-fecha_eliminacion'],
            },
        ),
        migrations.CreateModel(
            name='Disputa',
            fields=[
                ('id_disputa', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('motivo_publicador', models.TextField(blank=True, null=True)),
                ('motivo_trabajador', models.TextField(blank=True, null=True)),
                ('estado_disputa', models.CharField(default='Abierta', max_length=50)),
                ('resolucion_admin', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('trabajo', models.ForeignKey(db_column='id_trabajo', on_delete=django.db.models.deletion.CASCADE, related_name='disputas', to='api.trabajo')),
            ],
            options={
                'db_table': 'disputas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id_chat', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('trabajo', models.ForeignKey(blank=True, db_column='id_trabajo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='api.trabajo')),
            ],
            options={
                'db_table': 'chats',
                'ordering': ['-ultima_actualizacion'],
            },
        ),
        migrations.AddField(
            model_name='trabajo',
            name='publicador',
            field=models.ForeignKey(db_column='id_publicador', on_delete=django.db.models.deletion.CASCADE, related_name='trabajos_publicados', to='api.usuario'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='trabajador',
            field=models.ForeignKey(blank=True, db_column='id_trabajador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_asignados', to='api.usuario'),
        ),
        migrations.CreateModel(
            name='PuntuacionCategoria',
            fields=[
                ('pk', models.CompositePrimaryKey('id_categoria', 'usuario', blank=True, editable=False, primary_key=True, serialize=False)),
                ('id_categoria', models.CharField(max_length=255)),
                ('puntos', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='uid_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='puntuaciones_categorias', to='api.usuario')),
            ],
            options={
                'db_table': 'puntuaciones_categorias',
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('pk', models.CompositePrimaryKey('trabajador', 'trabajo', blank=True, editable=False, primary_key=True, serialize=False)),
                ('estado_postulacion', models.CharField(default='Pendiente', max_length=50)),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actividad', models.DateTimeField(auto_now=True)),
                ('trabajo', models.ForeignKey(db_column='id_trabajo', on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='api.trabajo')),
                ('trabajador', models.ForeignKey(db_column='uid_trabajador', on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='api.usuario')),
            ],
            options={
                'db_table': 'postulaciones',
                'ordering': ['-fecha_postulacion'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(blank=True, db_column='id_chat', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.chat')),
                ('trabajo', models.ForeignKey(blank=True, db_column='id_trabajo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.trabajo')),
                ('usuario', models.ForeignKey(db_column='uid_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='api.usuario')),
            ],
            options={
                'db_table': 'notificaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('favorito', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(db_column='uid_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago', to='api.usuario')),
            ],
            options={
                'db_table': 'metodos_pago',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('tipo_contenido', models.CharField(default='texto', max_length=50)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(db_column='id_chat', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='api.chat')),
                ('emisor', models.ForeignKey(db_column='id_emisor', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='api.usuario')),
                ('receptor', models.ForeignKey(db_column='id_receptor', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to='api.usuario')),
            ],
            options={
                'db_table': 'mensajes',
                'ordering': ['fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPago',
            fields=[
                ('id_pago', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_metodo', models.CharField(blank=True, max_length=255, null=True)),
                ('detalle_pago', models.TextField(blank=True, null=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='uid_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='historial_pagos', to='api.usuario')),
            ],
            options={
                'db_table': 'historial_pagos',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id_denuncia', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre_denunciante', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_denunciado', models.CharField(blank=True, max_length=255, null=True)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(default='pendiente', max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('denunciado', models.ForeignKey(db_column='id_denunciado', on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_recibidas', to='api.usuario')),
                ('denunciante', models.ForeignKey(db_column='id_denunciante', on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_realizadas', to='api.usuario')),
            ],
            options={
                'db_table': 'denuncias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('pk', models.CompositePrimaryKey('chat', 'usuario', blank=True, editable=False, primary_key=True, serialize=False)),
                ('id_trabajador', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(db_column='id_chat', on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='api.chat')),
                ('trabajo', models.ForeignKey(blank=True, db_column='id_trabajo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones', to='api.trabajo')),
                ('otro_usuario', models.ForeignKey(blank=True, db_column='id_otro_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_con_otro', to='api.usuario')),
                ('usuario', models.ForeignKey(db_column='uid_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='api.usuario')),
            ],
            options={
                'db_table': 'conversaciones',
                'ordering': ['-ultima_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='ChatUsuario',
            fields=[
                ('pk', models.CompositePrimaryKey('chat', 'usuario', blank=True, editable=False, primary_key=True, serialize=False)),
                ('chat', models.ForeignKey(db_column='id_chat', on_delete=django.db.models.deletion.CASCADE, to='api.chat')),
                ('usuario', models.ForeignKey(db_column='uid_usuario', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'chat_usuarios',
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='usuarios',
            field=models.ManyToManyField(related_name='chats', through='api.ChatUsuario', to='api.usuario'),
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id_log', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=100)),
                ('duracion', models.IntegerField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='uid_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='admin_logs', to='api.usuario')),
            ],
            options={
                'db_table': 'admin_logs',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id_valoracion', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('titulo_trabajo', models.CharField(blank=True, max_length=255, null=True)),
                ('puntuacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('receptor', models.ForeignKey(db_column='uid_receptor', on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_recibidas', to='api.usuario')),
                ('trabajo', models.ForeignKey(blank=True, db_column='id_trabajo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valoraciones', to='api.trabajo')),
                ('usuario_emisor', models.ForeignKey(db_column='id_usuario_emisor', on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_emitidas', to='api.usuario')),
            ],
            options={
                'db_table': 'valoraciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
